name: Build Android APK

on:
  push:
    branches:
      - main  # запускать сборку при коммитах в main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Кеширование Buildozer
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.local
          key: buildozer-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      - name: Сборка APK
        run: |
          buildozer android debug
          
      - name: Загрузка APK в артефакты
        uses: actions/upload-artifact@v3
        with:
          name: PokerTimer-APK
          path: bin/*.apk
